spring.application.name=hostel-booking-system
# Server configuration
server.port=8080

# Thymeleaf settings (default is fine, but you can customize)
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# Spring MVC static resources configuration
spring.web.resources.static-locations=classpath:/static/

# Enable detailed error messages (during development)
server.error.include-message=always
server.error.include-binding-errors=always
